---
- name: Copy scripts
  ansible.builtin.copy:
    content: "{{ item.content | default(omit) }}"
    src: "{{ item.src | default(omit) }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    mode: "{{ item.mode | default('0755') }}"
  loop: "{{ systemd_scripts }}"
  tags:
    - systemd_scripts

- name: Copy systemd units
  ansible.builtin.copy:
    content: "{{ item.content | default(omit) }}"
    src: "{{ item.src | default(omit) }}"
    dest: "/etc/systemd/system/{{ item.name }}"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ systemd_units }}"
  notify:
    - Reload systemd
  tags:
    - systemd_units

- name: Configure systemd units
  ansible.builtin.systemd:
    name: "{{ item.name }}"
    enabled: "{{ item.enabled | default(omit) }}"
    force: "{{ item.force | default(omit) }}"
    masked: "{{ item.masked | default(omit) }}"
    no_block: "{{ item.no_block | default(omit) }}"
    scope: "{{ item.scope | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
  loop: "{{ systemd_units }}"
  tags:
    - systemd_units
