---
- name: restart systemd units
  ansible.builtin.systemd:
    name: "{{ item.item.name }}"
    state: restarted
    daemon_reload: true
    enabled: true
  when: item.changed
  loop: "{{ __systemd_units_copied.results | default([]) }}"
